name: muslim_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  arabic_numbers: ^1.0.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_file_downloader: ^1.2.0
  gap: ^3.0.1
  google_fonts: ^6.1.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/quran-images/
    - assets/
